class MafiaString {
  static const String players = 'Игроки';
  static const String members = 'Члены клуба';
  static const String rules = 'Правила';
  static const String club = 'Клуб';
  static const String nickname = 'Никнейм';
  static const String city = 'Город';
  static const String president = 'Президент';
  static const String councilMember = 'Член совета клуба';
  static const String member = 'Член клуба';
  static const String player = 'Игрок';
  static const String selectRole = 'Выбрать роль';
  static const String balance = 'Баланс';
  static const String addPlayer = 'Добавить игрока';
  static const String email = 'Email';
  static const String password = 'Пароль';
  static const String logIn = 'Войти';
  static const String enterAsAdmin = 'Войти как администратор';
  static const String instagramButton = 'Instagram';
  static const String websiteButton = 'Website';
  static const String privatButton = 'Privat';
  static const String monobankButton = 'Monobank';
  static const String enterEmail = 'Введите корректный email!';
  static const String enterPassword = 'Введите корректный пароль!';
  static const String enterNickname = 'Укажите свободный никнейм!';
  static const String enterCity = 'Укажите город!';
  static const String enterBalance = 'Укажите баланс!';
  static const String save = 'Сохранить';
}